// Generated by mesh-api-gen from API.md; do not edit.

use serde::{Deserialize, Serialize};

/// Send a JSON-RPC request to a component Unix socket and return the unwrapped result
/// mesh-api: summary = "Send a JSON-RPC request to a component Unix socket and return the unwrapped result"
/// mesh-api: id = "ssh-mesh.jsonl_call"
/// mesh-api: component = "ssh-mesh"
/// mesh-api: method = "jsonl_call"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 4
/// mesh-api: method-index = 1
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct SshMeshJsonlCallRequest {
    /// API field `socket_path`.
    /// mesh-api-field: index = 1
    /// mesh-api-field: required = true
    /// mesh-api-field: position = 1
    pub socket_path: String,
    /// API field `method_name`.
    /// mesh-api-field: index = 2
    /// mesh-api-field: required = true
    /// mesh-api-field: position = 2
    pub method_name: String,
    /// API field `params`.
    /// mesh-api-field: index = 3
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub params: Option<serde_json::Value>,
}

/// Send a JSON-RPC request to a component Unix socket and return the unwrapped result
/// mesh-api: summary = "Send a JSON-RPC request to a component Unix socket and return the unwrapped result"
/// mesh-api: id = "ssh-mesh.jsonl_call"
/// mesh-api: component = "ssh-mesh"
/// mesh-api: method = "jsonl_call"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 4
/// mesh-api: method-index = 1
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct SshMeshJsonlCallResponse;

