// Generated by mesh-api-gen from API.md; do not edit.

use serde::{Deserialize, Serialize};

/// Send a JSON-RPC request to a component Unix socket and return the unwrapped result
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct SshMeshJsonlCallRequest {
    /// API field `socket_path`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub socket_path: Option<String>,
    /// API field `method_name`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub method_name: Option<String>,
    /// API field `params`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub params: Option<serde_json::Value>,
}

/// Send a JSON-RPC request to a component Unix socket and return the unwrapped result
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct SshMeshJsonlCallResponse;
