//! Standalone API artifact generator.
//!
//! This crate is a host build tool, never a runtime or firmware dependency.
//! API.md blocks are normative. Documented Rust structs are an optional input
//! which this tool turns into those checked-in blocks before normal generation.

use std::collections::{BTreeMap, BTreeSet};

use anyhow::{Context, Result, anyhow, bail};
use serde::Deserialize;
use serde_json::{Map, Value, json};

#[derive(Clone, Debug, Deserialize, Eq, PartialEq)]
pub struct ApiMethod {
    pub id: String,
    pub component: String,
    pub method: String,
    #[serde(default)]
    pub summary: String,
    #[serde(default = "public_visibility")]
    pub visibility: String,
    #[serde(rename = "component-index")]
    pub component_index: Option<u32>,
    #[serde(rename = "method-index")]
    pub method_index: Option<u32>,
    #[serde(default)]
    pub request: ApiShape,
    #[serde(default)]
    pub response: ApiShape,
}

fn public_visibility() -> String {
    "public".to_owned()
}

#[derive(Clone, Debug, Default, Deserialize, Eq, PartialEq)]
pub struct ApiShape {
    #[serde(default)]
    pub fields: Vec<ApiField>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq)]
pub struct ApiField {
    pub name: String,
    pub index: u32,
    #[serde(rename = "type")]
    pub value_type: String,
    #[serde(default)]
    pub required: bool,
    pub default: Option<Value>,
    pub position: Option<u8>,
}

/// Render deterministic Rust request and response data types from API methods.
///
/// The generated comments are intentionally understood by
/// [`api_markdown_from_rust`], so a generated file can be scanned later without
/// relying on proc macros or runtime reflection.
pub fn rust_api(methods: &[ApiMethod]) -> String {
    let mut output = String::from(
        "// Generated by mesh-api-gen from API.md; do not edit.\n\n\
use serde::{Deserialize, Serialize};\n\n",
    );
    for method in methods {
        render_rust_shape(&mut output, method, "request");
        render_rust_shape(&mut output, method, "response");
    }
    output
}

fn render_rust_shape(output: &mut String, method: &ApiMethod, shape: &str) {
    let fields = if shape == "request" {
        &method.request.fields
    } else {
        &method.response.fields
    };
    let struct_name = format!(
        "{}{}{}",
        pascal_identifier(&method.component),
        pascal_identifier(&method.method),
        if shape == "request" {
            "Request"
        } else {
            "Response"
        }
    );
    output.push_str(&format!("/// {}\n", method.summary));
    output.push_str(&format!("/// mesh-api: summary = {:?}\n", method.summary));
    output.push_str(&format!("/// mesh-api: id = {:?}\n", method.id));
    output.push_str(&format!(
        "/// mesh-api: component = {:?}\n",
        method.component
    ));
    output.push_str(&format!("/// mesh-api: method = {:?}\n", method.method));
    output.push_str(&format!(
        "/// mesh-api: visibility = {:?}\n",
        method.visibility
    ));
    if let Some(index) = method.component_index {
        output.push_str(&format!("/// mesh-api: component-index = {index}\n"));
    }
    if let Some(index) = method.method_index {
        output.push_str(&format!("/// mesh-api: method-index = {index}\n"));
    }
    if shape == "response" {
        output.push_str("/// mesh-api: shape = \"response\"\n");
    }
    output.push_str("#[derive(Clone, Debug, Deserialize, Serialize)]\n");
    if fields.is_empty() {
        output.push_str(&format!("pub struct {struct_name};\n\n"));
        return;
    }
    output.push_str(&format!("pub struct {struct_name} {{\n"));
    for field in fields {
        output.push_str(&format!("    /// API field `{}`.\n", field.name));
        output.push_str(&format!(
            "    /// mesh-api-field: index = {}\n",
            field.index
        ));
        output.push_str(&format!(
            "    /// mesh-api-field: required = {}\n",
            field.required
        ));
        if let Some(position) = field.position {
            output.push_str(&format!("    /// mesh-api-field: position = {position}\n"));
        }
        if let Some(default) = &field.default {
            output.push_str(&format!("    /// mesh-api-field: default = {}\n", default));
        }
        if !field.required {
            output.push_str("    #[serde(default, skip_serializing_if = \"Option::is_none\")]\n");
        }
        output.push_str(&format!(
            "    pub {}: {},\n",
            rust_field_name(&field.name),
            rust_value_type(&field.value_type, field.required)
        ));
    }
    output.push_str("}\n\n");
}

fn pascal_identifier(value: &str) -> String {
    value
        .split(|character: char| !character.is_ascii_alphanumeric())
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => format!("{}{}", first.to_ascii_uppercase(), chars.as_str()),
                None => String::new(),
            }
        })
        .collect()
}

fn rust_field_name(value: &str) -> String {
    match value {
        "type" | "match" | "ref" | "self" | "super" | "crate" => format!("r#{value}"),
        _ => value.to_owned(),
    }
}

fn rust_value_type(value_type: &str, required: bool) -> String {
    let value = match value_type {
        "bool" => "bool",
        "u8" => "u8",
        "u16" => "u16",
        "u32" => "u32",
        "u64" => "u64",
        "i8" => "i8",
        "i16" => "i16",
        "i32" => "i32",
        "i64" => "i64",
        "f32" => "f32",
        "f64" => "f64",
        "string" => "String",
        "bytes" => "Vec<u8>",
        "array" => "Vec<serde_json::Value>",
        "object" => "serde_json::Value",
        _ => "serde_json::Value",
    };
    if required {
        value.to_owned()
    } else {
        format!("Option<{value}>")
    }
}

/// Parse the `mesh-api` TOML fences from an API.md document.
pub fn parse_api_markdown(markdown: &str) -> Result<Vec<ApiMethod>> {
    let mut methods = Vec::new();
    let mut block = None;
    for line in markdown.lines() {
        if line.trim() == "```mesh-api" {
            if block.is_some() {
                bail!("nested mesh-api block");
            }
            block = Some(String::new());
            continue;
        }
        if line.trim() == "```"
            && let Some(block) = block.take()
        {
            let method = toml::from_str(&block).context("parse mesh-api TOML block")?;
            merge_method(&mut methods, method)?;
            continue;
        }
        if let Some(block) = &mut block {
            block.push_str(line);
            block.push('\n');
        }
    }
    if block.is_some() {
        bail!("unterminated mesh-api block");
    }
    validate(&methods)?;
    Ok(methods)
}

/// Rust authoring input may define request and response structs separately.
/// They become one API.md method when identity metadata matches and each shape
/// occurs exactly once; ordinary duplicate method declarations remain errors.
fn merge_method(methods: &mut Vec<ApiMethod>, method: ApiMethod) -> Result<()> {
    let Some(existing) = methods.iter_mut().find(|existing| existing.id == method.id) else {
        methods.push(method);
        return Ok(());
    };
    if existing.component != method.component
        || existing.method != method.method
        || existing.component_index != method.component_index
        || existing.method_index != method.method_index
        || existing.visibility != method.visibility
    {
        bail!("API id {} has incompatible duplicate metadata", method.id);
    }
    if !existing.summary.is_empty()
        && !method.summary.is_empty()
        && existing.summary != method.summary
    {
        bail!("API id {} has incompatible duplicate summaries", method.id);
    }
    if existing.summary.is_empty() {
        existing.summary = method.summary;
    }
    if !existing.request.fields.is_empty() && !method.request.fields.is_empty() {
        bail!("API id {} defines request fields more than once", method.id);
    }
    if !existing.response.fields.is_empty() && !method.response.fields.is_empty() {
        bail!(
            "API id {} defines response fields more than once",
            method.id
        );
    }
    if existing.request.fields.is_empty() {
        existing.request = method.request;
    }
    if existing.response.fields.is_empty() {
        existing.response = method.response;
    }
    Ok(())
}

/// Extract an API block from a Rust struct documented with `mesh-api` lines.
/// The intentionally small grammar avoids a runtime macro or an OpenAPI
/// dependency. Request fields opt in with adjacent `mesh-api-field` comments;
/// their Rust type supplies the generated `type` metadata.
pub fn api_markdown_from_rust(source: &str) -> Result<String> {
    let mut output = String::new();
    let mut annotations = Vec::new();
    let mut state: Option<RustApiStruct> = None;
    for line in source.lines() {
        let trimmed = line.trim_start();
        if let Some(current) = &mut state {
            if let Some(value) = trimmed.strip_prefix("/// mesh-api-field:") {
                current.field_annotations.push(value.trim().to_owned());
                continue;
            }
            if !current.field_annotations.is_empty() && trimmed.starts_with("#[") {
                continue;
            }
            if !current.field_annotations.is_empty()
                && let Some((name, value_type)) = rust_field(trimmed)
            {
                current.fields.push((
                    current.field_annotations.drain(..).collect(),
                    name.to_owned(),
                    rust_type(value_type).to_owned(),
                ));
            } else if !current.field_annotations.is_empty()
                && !trimmed.starts_with("///")
                && !trimmed.is_empty()
                && !trimmed.starts_with('#')
            {
                bail!("mesh-api-field annotations must immediately document a Rust field");
            }
            current.depth += brace_delta(trimmed);
            if current.depth <= 0 {
                if !current.field_annotations.is_empty() {
                    bail!("mesh-api-field annotations are not followed by a Rust field");
                }
                render_rust_api_struct(&mut output, state.take().expect("state exists"))?;
            }
            continue;
        }
        if let Some(value) = trimmed.strip_prefix("/// mesh-api:") {
            annotations.push(value.trim().to_owned());
            continue;
        }
        if !annotations.is_empty() && trimmed.contains("struct ") {
            let depth = brace_delta(trimmed);
            let current = RustApiStruct {
                annotations: std::mem::take(&mut annotations),
                fields: Vec::new(),
                field_annotations: Vec::new(),
                depth,
            };
            if depth <= 0 {
                render_rust_api_struct(&mut output, current)?;
            } else {
                state = Some(current);
            }
        } else if !annotations.is_empty() && trimmed.starts_with("#[") {
            continue;
        } else if !annotations.is_empty()
            && !trimmed.starts_with("///")
            && !trimmed.starts_with('#')
            && !trimmed.is_empty()
        {
            bail!("mesh-api annotations must immediately document a struct");
        }
    }
    if state.is_some() {
        bail!("mesh-api annotated struct is not terminated");
    }
    if !annotations.is_empty() {
        bail!("mesh-api annotations are not followed by a struct");
    }
    // Parse now so source annotations cannot generate an invalid API.md.
    parse_api_markdown(&output)?;
    Ok(output)
}

/// Bootstrap reviewed `mesh-api` blocks from an older hand-maintained tools
/// catalog. This deliberately does not assign numeric IDs: maintainers must
/// review and add stable component/method/field indices before a client will
/// select tagged CBOR for the method.
pub fn api_markdown_from_tools_json(value: &Value) -> Result<String> {
    api_markdown_from_tools_json_for_component(value, None)
}

/// Like [`api_markdown_from_tools_json`] but supplies a component for legacy
/// catalogs whose method names are bare verbs such as `status` or `start`.
pub fn api_markdown_from_tools_json_for_component(
    value: &Value,
    default_component: Option<&str>,
) -> Result<String> {
    let tools = value
        .as_array()
        .or_else(|| value.get("tools").and_then(Value::as_array))
        .ok_or_else(|| anyhow!("tools catalog must be an array or object with tools"))?;
    let mut output = String::new();
    for tool in tools {
        let name = tool
            .get("name")
            .and_then(Value::as_str)
            .ok_or_else(|| anyhow!("tools catalog entry lacks name"))?;
        let (component, method) = name
            .split_once('.')
            .unwrap_or((default_component.unwrap_or(""), name));
        let id = if component.is_empty() {
            method.to_owned()
        } else {
            format!("{component}.{method}")
        };
        output.push_str("```mesh-api\n");
        output.push_str(&format!("id = {:?}\n", id));
        output.push_str(&format!("component = {:?}\n", component));
        output.push_str(&format!("method = {:?}\n", method));
        output.push_str("visibility = \"public\"\n");
        if let Some(summary) = tool.get("description").and_then(Value::as_str) {
            output.push_str(&format!("summary = {:?}\n", summary));
        }
        let required = tool
            .pointer("/inputSchema/required")
            .and_then(Value::as_array)
            .into_iter()
            .flatten()
            .filter_map(Value::as_str)
            .collect::<BTreeSet<_>>();
        if let Some(properties) = tool
            .pointer("/inputSchema/properties")
            .and_then(Value::as_object)
        {
            for (field, property) in properties {
                output.push_str("\n[[request.fields]]\n");
                output.push_str(&format!("name = {:?}\n", field));
                // Index zero is rejected by the normal parser; leaving it out
                // forces a conscious stable-number allocation during review.
                output.push_str(&format!(
                    "type = {:?}\n",
                    schema_type(property).unwrap_or("object")
                ));
                if required.contains(field.as_str()) {
                    output.push_str("required = true\n");
                }
            }
        }
        output.push_str("```\n\n");
    }
    Ok(output)
}

fn schema_type(value: &Value) -> Option<&str> {
    let value = value.get("type")?;
    match value {
        Value::String(value) => Some(schema_primitive(value)),
        Value::Array(values) => values
            .iter()
            .filter_map(Value::as_str)
            .map(schema_primitive)
            .next(),
        _ => None,
    }
}

fn schema_primitive(value: &str) -> &'static str {
    match value {
        "boolean" => "bool",
        "integer" => "i64",
        "number" => "f64",
        "string" => "string",
        "array" => "array",
        "object" => "object",
        _ => "object",
    }
}

struct RustApiStruct {
    annotations: Vec<String>,
    fields: Vec<(Vec<String>, String, String)>,
    field_annotations: Vec<String>,
    depth: i32,
}

fn render_rust_api_struct(output: &mut String, source: RustApiStruct) -> Result<()> {
    output.push_str("```mesh-api\n");
    let mut shape = "request";
    for annotation in &source.annotations {
        if let Some(value) = annotation.strip_prefix("shape =") {
            shape = value.trim().trim_matches('"');
            continue;
        }
        output.push_str(&annotation);
        output.push('\n');
    }
    if !matches!(shape, "request" | "response") {
        bail!("mesh-api shape must be request or response");
    }
    for (annotations, name, value_type) in source.fields {
        output.push_str(&format!("\n[[{shape}.fields]]\n"));
        output.push_str(&format!("name = {:?}\n", name));
        output.push_str(&format!("type = {:?}\n", value_type));
        for annotation in annotations {
            output.push_str(&annotation);
            output.push('\n');
        }
    }
    output.push_str("```\n\n");
    Ok(())
}

fn brace_delta(value: &str) -> i32 {
    value.bytes().fold(0, |delta, byte| match byte {
        b'{' => delta + 1,
        b'}' => delta - 1,
        _ => delta,
    })
}

fn rust_field(value: &str) -> Option<(&str, &str)> {
    let (name, value_type) = value.trim().trim_end_matches(',').split_once(':')?;
    let name = name.trim();
    let name = if let Some(name) = name.strip_prefix("pub(") {
        name.split_once(')')?.1.trim()
    } else {
        name.strip_prefix("pub ").unwrap_or(name)
    };
    let name = name.strip_prefix("r#").unwrap_or(name);
    (!name.is_empty() && !value_type.trim().is_empty()).then_some((name, value_type.trim()))
}

fn rust_type(value: &str) -> &str {
    let value = value.trim();
    let value = value
        .strip_prefix("Option<")
        .and_then(|value| value.strip_suffix('>'))
        .unwrap_or(value);
    match value {
        "String" | "&str" => "string",
        "Vec<u8>" | "&[u8]" | "Bytes" => "bytes",
        "bool" => "bool",
        "u8" | "u16" | "u32" | "u64" | "i8" | "i16" | "i32" | "i64" | "f32" | "f64" => value,
        value if value.starts_with("Vec<") => "array",
        _ => "object",
    }
}

pub fn tools_json(methods: &[ApiMethod]) -> Value {
    Value::Array(
        methods
            .iter()
            .filter(|method| method.visibility == "public")
            .map(|method| {
                let mut tool = Map::new();
                tool.insert(
                    "name".to_owned(),
                    Value::String(format!("{}.{}", method.component, method.method)),
                );
                tool.insert(
                    "description".to_owned(),
                    Value::String(method.summary.clone()),
                );
                if let Some(index) = method.component_index {
                    tool.insert("x-component-index".to_owned(), Value::from(index));
                }
                if let Some(index) = method.method_index {
                    tool.insert("x-method-index".to_owned(), Value::from(index));
                }
                tool.insert("inputSchema".to_owned(), shape_schema(&method.request));
                tool.insert("outputSchema".to_owned(), shape_schema(&method.response));
                Value::Object(tool)
            })
            .collect(),
    )
}

/// Overlay reviewed generated entries onto a legacy tools catalog.
///
/// This enables incremental migration: a service may publish stable numeric
/// tags for a reviewed subset while retaining older tools as visible,
/// schema-less JSON-RPC operations. Generated entries replace a legacy entry
/// with the same fully-qualified `name`; they do not invent IDs for the rest.
pub fn merge_tools_json(base: &Value, methods: &[ApiMethod]) -> Result<Value> {
    let base = base
        .as_array()
        .or_else(|| base.get("tools").and_then(Value::as_array))
        .context("base tools catalog must be an array or object with tools")?;
    let generated = tools_json(methods);
    let generated = generated
        .as_array()
        .expect("tools_json always returns an array");
    let replacements: BTreeMap<_, _> = generated
        .iter()
        .filter_map(|tool| {
            tool.get("name")
                .and_then(Value::as_str)
                .map(|name| (name, tool))
        })
        .collect();
    let mut merged = Vec::with_capacity(base.len() + generated.len());
    let mut replaced = BTreeSet::new();
    for tool in base {
        let Some(name) = tool.get("name").and_then(Value::as_str) else {
            bail!("base tools catalog entry has no string name");
        };
        let replacement = replacements.get(name).copied().or_else(|| {
            // Legacy catalogs commonly spell a service method as `status`
            // or `raw.check`, while the tagged API uses `lmesh.status` or
            // `wifi.raw.check`. Overlay it only when exactly one reviewed
            // entry has that suffix; ambiguity leaves the legacy entry alone.
            let suffix = format!(".{name}");
            let matches: Vec<_> = generated
                .iter()
                .filter(|tool| {
                    tool["name"]
                        .as_str()
                        .is_some_and(|candidate| candidate.ends_with(&suffix))
                })
                .collect();
            (matches.len() == 1).then(|| matches[0])
        });
        if let Some(replacement) = replacement {
            merged.push((*replacement).clone());
            replaced.insert(
                replacement["name"]
                    .as_str()
                    .expect("generated tool always has a name"),
            );
        } else {
            merged.push(tool.clone());
        }
    }
    for tool in generated {
        let name = tool["name"]
            .as_str()
            .expect("generated tool always has a name");
        if !replaced.contains(name) {
            merged.push(tool.clone());
        }
    }
    Ok(Value::Array(merged))
}

/// Produce a standard JSON Schema for text/JSON gateways. The numeric wire
/// identities remain explicit `x-*` metadata rather than a JSON Schema or
/// protobuf claim.
pub fn json_schema(methods: &[ApiMethod]) -> Value {
    let variants: Vec<_> = methods
        .iter()
        .filter(|method| method.visibility == "public")
        .map(|method| {
            let mut schema = shape_schema(&method.request);
            let object = schema
                .as_object_mut()
                .expect("shape_schema always creates an object");
            let properties = object
                .get_mut("properties")
                .and_then(Value::as_object_mut)
                .expect("shape_schema always creates properties");
            properties.insert(
                "method".to_owned(),
                json!({"const": format!("{}.{}", method.component, method.method)}),
            );
            let required = object
                .get_mut("required")
                .and_then(Value::as_array_mut)
                .expect("shape_schema always creates required");
            required.insert(0, Value::String("method".to_owned()));
            if let Some(index) = method.component_index {
                object.insert("x-component-index".to_owned(), Value::from(index));
            }
            if let Some(index) = method.method_index {
                object.insert("x-method-index".to_owned(), Value::from(index));
            }
            schema
        })
        .collect();
    json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "oneOf": variants,
    })
}

fn shape_schema(shape: &ApiShape) -> Value {
    let mut properties = Map::new();
    let mut required = Vec::new();
    for field in &shape.fields {
        let mut property = Map::new();
        property.insert(
            "type".to_owned(),
            Value::String(json_type(&field.value_type).to_owned()),
        );
        property.insert("x-protobuf-index".to_owned(), Value::from(field.index));
        property.insert(
            "x-protobuf-type".to_owned(),
            Value::String(field.value_type.clone()),
        );
        if let Some(position) = field.position {
            property.insert("x-cli-position".to_owned(), Value::from(position));
        }
        if let Some(default) = &field.default {
            property.insert("default".to_owned(), default.clone());
        }
        if field.required {
            required.push(Value::String(field.name.clone()));
        }
        properties.insert(field.name.clone(), Value::Object(property));
    }
    json!({"type": "object", "properties": properties, "required": required})
}

fn json_type(value_type: &str) -> &'static str {
    match value_type {
        "bool" => "boolean",
        "u8" | "u16" | "u32" | "u64" | "i8" | "i16" | "i32" | "i64" => "integer",
        "f32" | "f64" => "number",
        "bytes" => "string",
        "array" => "array",
        "object" => "object",
        _ => "string",
    }
}

pub fn rust_ids(methods: &[ApiMethod]) -> String {
    let mut output = String::from("// Generated by mesh-api-gen; do not edit.\n\n");
    let mut emitted_components = BTreeSet::new();
    for method in methods {
        let component = identifier(&method.component);
        let name = identifier(&format!("{}_{}", method.component, method.method));
        if let Some(index) = method.component_index
            && emitted_components.insert(component.clone())
        {
            output.push_str(&format!(
                "pub const COMPONENT_{component}: u32 = {index};\n"
            ));
        }
        if let Some(index) = method.method_index {
            output.push_str(&format!("pub const METHOD_{name}: u32 = {index};\n"));
        }
        for field in &method.request.fields {
            output.push_str(&format!(
                "pub const FIELD_{}_{}: u32 = {};\n",
                name,
                identifier(&field.name),
                field.index
            ));
        }
    }
    output
}

fn identifier(value: &str) -> String {
    value
        .chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() {
                character.to_ascii_uppercase()
            } else {
                '_'
            }
        })
        .collect()
}

fn validate(methods: &[ApiMethod]) -> Result<()> {
    let mut ids = BTreeSet::new();
    let mut wire_methods = BTreeSet::new();
    let mut components = BTreeMap::new();
    for method in methods {
        if !ids.insert(&method.id) {
            bail!("duplicate API id {}", method.id);
        }
        if method.component.is_empty() || method.method.is_empty() {
            bail!("{} has an empty component or method", method.id);
        }
        if !matches!(method.visibility.as_str(), "public" | "private") {
            bail!("{} has invalid visibility {}", method.id, method.visibility);
        }
        if let Some(component_index) = method.component_index
            && let Some(previous) = components.insert(component_index, &method.component)
            && previous != &method.component
        {
            bail!(
                "component index {component_index} is used by both {previous} and {}",
                method.component
            );
        }
        if let (Some(component), Some(method_index)) = (method.component_index, method.method_index)
            && !wire_methods.insert((component, method_index))
        {
            bail!("duplicate component/method index {component}/{method_index}");
        }
        validate_fields(&method.id, &method.request.fields)?;
        validate_fields(&method.id, &method.response.fields)?;
    }
    Ok(())
}

fn validate_fields(id: &str, fields: &[ApiField]) -> Result<()> {
    let mut indices = BTreeSet::new();
    let mut positions = BTreeSet::new();
    for field in fields {
        if field.index == 0 || !indices.insert(field.index) {
            bail!("{id} has duplicate or zero field index {}", field.index);
        }
        if !matches!(
            field.value_type.as_str(),
            "bool"
                | "u8"
                | "u16"
                | "u32"
                | "u64"
                | "i8"
                | "i16"
                | "i32"
                | "i64"
                | "f32"
                | "f64"
                | "string"
                | "bytes"
                | "array"
                | "object"
        ) {
            bail!(
                "{id}.{} has unsupported type {}",
                field.name,
                field.value_type
            );
        }
        if let Some(position) = field.position {
            if !(1..=3).contains(&position) || !positions.insert(position) {
                bail!(
                    "{id}.{} has invalid or duplicate CLI position {position}",
                    field.name
                );
            }
        }
    }
    Ok(())
}

pub fn parse_required_path(value: Option<String>, name: &str) -> Result<String> {
    value.ok_or_else(|| anyhow!("{name} is required"))
}

#[cfg(test)]
mod tests {
    use super::*;

    const API: &str = r#"
```mesh-api
id = "wifi.raw.check"
component = "wifi"
method = "raw.check"
component-index = 7
method-index = 2
summary = "Read radio state"

[[request.fields]]
name = "channel"
index = 1
type = "u8"
required = true

[[request.fields]]
name = "verbose"
index = 2
type = "bool"
position = 1
```
"#;

    #[test]
    fn generates_catalog_and_ids_from_api_md() {
        let mut methods = parse_api_markdown(API).unwrap();
        let tools = tools_json(&methods);
        assert_eq!(tools[0]["x-component-index"], 7);
        assert_eq!(
            tools[0]["inputSchema"]["properties"]["channel"]["x-protobuf-index"],
            1
        );
        assert!(rust_ids(&methods).contains("METHOD_WIFI_RAW_CHECK: u32 = 2"));
        let mut another = methods[0].clone();
        another.id = "wifi.raw.other".to_owned();
        another.method = "raw.other".to_owned();
        another.method_index = Some(3);
        methods.push(another);
        assert_eq!(rust_ids(&methods).matches("COMPONENT_WIFI").count(), 1);
        assert_eq!(
            json_schema(&methods)["oneOf"][0]["properties"]["method"]["const"],
            "wifi.raw.check"
        );
    }

    #[test]
    fn container_fields_keep_their_json_schema_shape() {
        let methods = parse_api_markdown(
            r#"
```mesh-api
id = "service.configure"
component = "service"
method = "configure"
component-index = 9
method-index = 1
[request]
fields = [
  { name = "args", index = 1, type = "array" },
  { name = "env", index = 2, type = "object" },
]
```
"#,
        )
        .unwrap();
        let properties = &tools_json(&methods)[0]["inputSchema"]["properties"];
        assert_eq!(properties["args"]["type"], "array");
        assert_eq!(properties["env"]["type"], "object");
    }

    #[test]
    fn reviewed_api_entries_overlay_but_do_not_number_legacy_tools() {
        let methods = parse_api_markdown(API).unwrap();
        let merged = merge_tools_json(
            &json!([
                {"name": "raw.check", "title": "old"},
                {"name": "legacy.inspect", "title": "legacy"}
            ]),
            &methods,
        )
        .unwrap();
        assert_eq!(merged.as_array().unwrap().len(), 2);
        assert_eq!(merged[0]["name"], "wifi.raw.check");
        assert_eq!(merged[0]["x-component-index"], 7);
        assert!(merged[1].get("x-component-index").is_none());
    }

    #[test]
    fn rust_annotations_generate_valid_api_blocks() {
        let source = r#"
/// mesh-api: id = "wifi.raw.check"
/// mesh-api: component = "wifi"
/// mesh-api: method = "raw.check"
pub struct RawCheck {
    /// mesh-api-field: index = 1
    /// mesh-api-field: required = true
    pub channel: u8,
    /// mesh-api-field: index = 2
    pub payload: Vec<u8>,
}
/// mesh-api: id = "wifi.raw.check"
/// mesh-api: component = "wifi"
/// mesh-api: method = "raw.check"
/// mesh-api: shape = "response"
pub struct RawCheckResponse {
    /// mesh-api-field: index = 1
    pub ok: bool,
}
"#;
        let generated = api_markdown_from_rust(source).unwrap();
        assert!(generated.contains("```mesh-api"));
        let methods = parse_api_markdown(&generated).unwrap();
        assert_eq!(methods.len(), 1);
        assert_eq!(methods[0].request.fields[0].value_type, "u8");
        assert_eq!(methods[0].request.fields[1].value_type, "bytes");
        assert_eq!(methods[0].response.fields[0].name, "ok");
    }

    #[test]
    fn generated_rust_round_trips_to_the_same_api_model() {
        let methods = parse_api_markdown(API).unwrap();
        let generated = rust_api(&methods);
        assert!(generated.contains("#[derive(Clone, Debug, Deserialize, Serialize)]"));
        assert!(generated.contains("pub struct WifiRawCheckRequest"));
        assert_eq!(
            parse_api_markdown(&api_markdown_from_rust(&generated).unwrap()).unwrap(),
            methods
        );
    }

    #[test]
    fn private_methods_keep_ids_but_are_not_gateway_catalog_entries() {
        let methods = parse_api_markdown(
            r#"
```mesh-api
id = "wifi.private"
component = "wifi"
method = "private"
visibility = "private"
component-index = 1
method-index = 2
```
"#,
        )
        .unwrap();
        assert_eq!(tools_json(&methods), Value::Array(Vec::new()));
        assert!(rust_ids(&methods).contains("METHOD_WIFI_PRIVATE"));
    }

    #[test]
    fn legacy_catalog_import_requires_reviewed_numeric_indices() {
        let imported = api_markdown_from_tools_json(&json!([{
            "name": "mesh-init.status",
            "description": "Get state",
            "inputSchema": {"properties": {
                "name": {"type": ["string", "null"]}
            }}
        }]))
        .unwrap();
        assert!(imported.contains("component = \"mesh-init\""));
        assert!(imported.contains("name = \"name\""));
        // No field ID has been invented; the normal source parser therefore
        // correctly refuses the unreviewed migration draft.
        assert!(parse_api_markdown(&imported).is_err());

        let bare = api_markdown_from_tools_json_for_component(
            &json!([{"name": "status", "inputSchema": {}}]),
            Some("mesh-init"),
        )
        .unwrap();
        assert!(bare.contains("component = \"mesh-init\""));
    }
}
