[Service]
ExecStart = "ssh-mesh"

[Socket]
Accept = false

[[Socket.Listen]]
Type = "stream"
Address = "0.0.0.0:15022"
Name = "ssh"

[[Socket.Listen]]
Type = "stream"
Address = "0.0.0.0:15443"
Name = "mesh-mtls"

[[Socket.Listen]]
Type = "stream"
Address = "0.0.0.0:80"
Name = "http"

[[Socket.Listen]]
Type = "stream"
Address = "0.0.0.0:443"
Name = "https"

[[Socket.Listen]]
Type = "stream"
Address = "127.0.0.1:15080"
Name = "admin"

[[Socket.Listen]]
Type = "stream"
Address = "/run/mesh/ssh-mesh/mesh.sock"
Name = "jsonl"

[[Socket.Listen]]
Type = "stream"
Address = "/home/ssh-mesh/run/ssh-mesh/trusted-ssh.sock"
Name = "ssh-uds"

[[Socket.Listen]]
Type = "stream"
Address = "vsock:2:15022"
Name = "vsock"
