[Service]

ExecStart = "mesh9p /home/system:/host2:rw /opt"
OOMScoreAdjust = -600
[Resources]
MemoryMin = "64M"
MemoryHigh = "128M"
CPUWeight = 50

[Environment]
RUST_LOG = "info"

[Socket]
ListenStream = "15102"
Accept = true
