# Standalone ssh mesh jumphost - will just forward SSH requests.
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sshm
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/launch-stage: ALPHA
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2

        # Attach to the VPC (no connector)
        # run.googleapis.com/network-interfaces: '[{"network": "default", "subnetwork": "default"}]'

        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '1'
        run.googleapis.com/cpu-throttling: 'false'

    spec:
      containerConcurrency: 1000
      timeoutSeconds: 900
      containers:
        - name: app
          image: docker.io/costinm/sshm:h2c-v3
          ports:
            - name: h2c
              containerPort: 8080
          env:
            - name: SSH_DEFAULT_H2
              value: https://httpbin.org

            - name: SSH_DEFAULT_HTTP
              value: https://httpbin.org

            # Trusted CA keys and authorized keys passed via environment variable
            - name: SSH_AUTHORIZED_CAS
              value: |
                ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDu9dWIA381ojxsUS8i0VJv0ED5Ac2zRFX1JijLjAO5HywPJ5a3CMM0NrXH5GqSoyDB/j92/Ta/f0QFAQZDhiFQ= ca.s.webinf.duckdns.org

            - name: SSH_AUTHORIZED_KEYS
              value: |
                ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBBRjGteKUhj757bQ8qaju5bvgWjoaZuGLvkq/Xnhr/LDW//qAk8O3v+RswbaCodSjKI6SDgFKl6samdUhP+kUwI= costin@costin15

            - name: MESH_SSH_MESH_UID
              value: "1001"

            - name: RUST_LOG
              value: "info"

            - name: DEPLOY
              value: "${DEPLOY}"

          resources:
            limits:
              cpu: '1'
              memory: 1G
  traffic:
    - percent: 100
      latestRevision: true
