[Service]

ExecStart = "mesh9p /home/system:/host3-vm:rw /tmp/mesh/9p:/imports:rw /opt"
OOMScoreAdjust = -600
[Resources]
MemoryMin = "64M"
MemoryHigh = "128M"
CPUWeight = 50

[Environment]
RUST_LOG = "info"

[Socket]
ListenStream = "15103"
Accept = true
