[Service]
ExecStart = "ssh-mesh"

[Socket]
Accept = false

[[Socket.Listen]]
Type = "stream"
Address = "0.0.0.0:15022"

[[Socket.Listen]]
Type = "stream"
Address = "0.0.0.0:15443"

[[Socket.Listen]]
Type = "stream"
Address = "0.0.0.0:80"

[[Socket.Listen]]
Type = "stream"
Address = "0.0.0.0:443"

[[Socket.Listen]]
Type = "stream"
Address = "127.0.0.1:15080"

[[Socket.Listen]]
Type = "stream"
Address = "/home/ssh-mesh/run/ssh-mesh/jsonl.sock"

[[Socket.Listen]]
Type = "stream"
Address = "/home/ssh-mesh/run/ssh-mesh/trusted-ssh.sock"

[[Socket.Listen]]
Type = "stream"
Address = "vsock:2:15022"
