// Generated by mesh-api-gen from API.md; do not edit.

use serde::{Deserialize, Serialize};

/// Receive a supervisor freeze or unfreeze notification
/// mesh-api: summary = "Receive a supervisor freeze or unfreeze notification"
/// mesh-api: id = "mesh.lifecycle"
/// mesh-api: component = "mesh"
/// mesh-api: method = "lifecycle"
/// mesh-api: visibility = "private"
/// mesh-api: component-index = 1
/// mesh-api: method-index = 3
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshLifecycleRequest {
    /// API field `action`.
    /// mesh-api-field: index = 1
    /// mesh-api-field: required = true
    pub action: String,
    /// API field `cause`.
    /// mesh-api-field: index = 2
    /// mesh-api-field: required = true
    pub cause: String,
    /// API field `observed`.
    /// mesh-api-field: index = 3
    /// mesh-api-field: required = true
    pub observed: bool,
}

/// Receive a supervisor freeze or unfreeze notification
/// mesh-api: summary = "Receive a supervisor freeze or unfreeze notification"
/// mesh-api: id = "mesh.lifecycle"
/// mesh-api: component = "mesh"
/// mesh-api: method = "lifecycle"
/// mesh-api: visibility = "private"
/// mesh-api: component-index = 1
/// mesh-api: method-index = 3
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshLifecycleResponse {
    /// API field `subscribers`.
    /// mesh-api-field: index = 1
    /// mesh-api-field: required = true
    pub subscribers: u64,
}

/// Return MCP initialization info
/// mesh-api: summary = "Return MCP initialization info"
/// mesh-api: id = "mesh.mcp.initialize"
/// mesh-api: component = "mesh"
/// mesh-api: method = "initialize"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 1
/// mesh-api: method-index = 1
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshInitializeRequest;

/// Return MCP initialization info
/// mesh-api: summary = "Return MCP initialization info"
/// mesh-api: id = "mesh.mcp.initialize"
/// mesh-api: component = "mesh"
/// mesh-api: method = "initialize"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 1
/// mesh-api: method-index = 1
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshInitializeResponse;

/// List registered MCP tools from catalog
/// mesh-api: summary = "List registered MCP tools from catalog"
/// mesh-api: id = "mesh.mcp.tools_list"
/// mesh-api: component = "mesh"
/// mesh-api: method = "tools/list"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 1
/// mesh-api: method-index = 2
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshToolsListRequest;

/// List registered MCP tools from catalog
/// mesh-api: summary = "List registered MCP tools from catalog"
/// mesh-api: id = "mesh.mcp.tools_list"
/// mesh-api: component = "mesh"
/// mesh-api: method = "tools/list"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 1
/// mesh-api: method-index = 2
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshToolsListResponse;

/// Subscribe to live trace log event stream
/// mesh-api: summary = "Subscribe to live trace log event stream"
/// mesh-api: id = "mesh.trace.subscribe"
/// mesh-api: component = "trace"
/// mesh-api: method = "subscribe"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 2
/// mesh-api: method-index = 1
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct TraceSubscribeRequest;

/// Subscribe to live trace log event stream
/// mesh-api: summary = "Subscribe to live trace log event stream"
/// mesh-api: id = "mesh.trace.subscribe"
/// mesh-api: component = "trace"
/// mesh-api: method = "subscribe"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 2
/// mesh-api: method-index = 1
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct TraceSubscribeResponse;

/// Dynamically update tracing filter level
/// mesh-api: summary = "Dynamically update tracing filter level"
/// mesh-api: id = "mesh.trace.set_level"
/// mesh-api: component = "trace"
/// mesh-api: method = "set_level"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 2
/// mesh-api: method-index = 2
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct TraceSetLevelRequest {
    /// API field `level`.
    /// mesh-api-field: index = 1
    /// mesh-api-field: required = true
    /// mesh-api-field: position = 1
    pub level: String,
}

/// Dynamically update tracing filter level
/// mesh-api: summary = "Dynamically update tracing filter level"
/// mesh-api: id = "mesh.trace.set_level"
/// mesh-api: component = "trace"
/// mesh-api: method = "set_level"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 2
/// mesh-api: method-index = 2
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct TraceSetLevelResponse;

/// Get current tracing filter level info
/// mesh-api: summary = "Get current tracing filter level info"
/// mesh-api: id = "mesh.trace.get_level"
/// mesh-api: component = "trace"
/// mesh-api: method = "get_level"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 2
/// mesh-api: method-index = 3
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct TraceGetLevelRequest;

/// Get current tracing filter level info
/// mesh-api: summary = "Get current tracing filter level info"
/// mesh-api: id = "mesh.trace.get_level"
/// mesh-api: component = "trace"
/// mesh-api: method = "get_level"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 2
/// mesh-api: method-index = 3
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct TraceGetLevelResponse;
