// Generated by mesh-api-gen; do not edit.

pub const COMPONENT_MESH: u32 = 1;
pub const METHOD_MESH_INITIALIZE: u32 = 1;
pub const METHOD_MESH_TOOLS_LIST: u32 = 2;
pub const COMPONENT_TRACE: u32 = 2;
pub const METHOD_TRACE_SUBSCRIBE: u32 = 1;
pub const METHOD_TRACE_SET_LEVEL: u32 = 2;
pub const FIELD_TRACE_SET_LEVEL_LEVEL: u32 = 1;
pub const METHOD_TRACE_GET_LEVEL: u32 = 3;
