## Same base as Istio proxyless
FROM debian:11-slim  AS base

RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-install -y dropbear


FROM gcr.io/distroless/static-debian11@sha256:1061399c202961ab567994c1bd42327bccd6380a345dcf88bf9ad7d5c8e29571 as distroless_source

COPY from=base /usr/sbin/sshd /usr/sbin/
COPY from=base /usr/bin/ssh /usr/bin/
