use std::net::IpAddr;
use std::sync::Arc;

use mesh::tun::{TunDnsHandler, TunTcpHandler, TunUdpHandler};
use tcp_rewrite::{TcpRewriteConfig, TcpRewriter};
use tokio::sync::mpsc;

pub mod control;
pub mod flow;
pub mod injector;
pub mod packet;
pub mod policy;
pub mod stats;
pub mod tcp_proxy;
pub mod tcp_rewrite;
pub mod telemetry;
pub mod uds;
pub mod vhost_user;

/// Configuration for MeshTun.
#[derive(Debug, Clone)]
pub struct MeshTunConfig {
    /// TUN interface name. Ignored if `fd` is set.
    pub name: Option<String>,
    /// Pre-opened TUN file descriptor, used by Android VPN integration.
    pub fd: Option<i32>,
    /// Local IP address reserved for this capture endpoint.
    pub address: IpAddr,
    /// Network prefix length.
    pub prefix_len: u8,
    /// MTU for packet buffers and created TUN devices.
    pub mtu: usize,
    /// Workload identity attached to flows from this capture instance.
    pub vm_id: String,
    /// Enable passt-style TCP source tracking and packet rewrite.
    pub tcp_rewrite: bool,
    /// TCP rewrite settings.
    pub tcp_rewrite_config: TcpRewriteConfig,
}

impl Default for MeshTunConfig {
    fn default() -> Self {
        Self {
            name: None,
            fd: None,
            address: "10.5.0.1".parse().unwrap(),
            prefix_len: 16,
            mtu: 1500,
            vm_id: "default".to_string(),
            tcp_rewrite: true,
            tcp_rewrite_config: TcpRewriteConfig::default(),
        }
    }
}

pub struct MeshTun {
    config: MeshTunConfig,
}

impl MeshTun {
    pub fn new(config: MeshTunConfig) -> Result<Self, anyhow::Error> {
        Ok(Self { config })
    }

    /// Create a MeshTun from an Android VPN/TUN file descriptor.
    ///
    /// The caller remains responsible for passing a valid TUN fd. The fd is
    /// handed to `tun-rs` when [`MeshTun::run`] is called.
    ///
    /// # Safety
    ///
    /// The caller must ensure that `fd` is a valid file descriptor for a TUN/VPN device.
    pub unsafe fn from_fd(fd: i32) -> Result<Self, anyhow::Error> {
        let config = MeshTunConfig {
            fd: Some(fd),
            ..MeshTunConfig::default()
        };
        Ok(Self { config })
    }

    /// Start packet routing over a real TUN device or pre-opened fd.
    pub async fn run(
        self,
        tcp_handler: Arc<dyn TunTcpHandler>,
        udp_handler: Arc<dyn TunUdpHandler>,
        dns_handler: Arc<dyn TunDnsHandler>,
    ) -> Result<Arc<dyn mesh::tun::TunInjector>, anyhow::Error> {
        let (tun_tx, tun_rx) = mpsc::unbounded_channel::<Vec<u8>>();
        let (device_tx, mut device_rx) = mpsc::unbounded_channel::<Vec<u8>>();
        let injector = Arc::new(injector::MeshTunInjector::new(device_tx.clone()));
        let tcp_rewriter = self.tcp_rewriter()?;

        let tun = self.open_tun_device()?;
        let tun_arc = Arc::new(tun);
        let tun_read = tun_arc.clone();
        let tun_write = tun_arc;
        let mtu = self.config.mtu.max(1500);

        tokio::spawn(async move {
            let mut buf = vec![0u8; mtu.max(65535)];
            loop {
                match tun_read.recv(&mut buf).await {
                    Ok(n) => {
                        let _ = tun_tx.send(buf[..n].to_vec());
                    }
                    Err(error) => {
                        tracing::error!(%error, "TUN read stopped");
                        break;
                    }
                }
            }
        });

        tokio::spawn(async move {
            while let Some(packet) = device_rx.recv().await {
                if let Err(error) = tun_write.send(&packet).await {
                    tracing::error!(%error, "TUN write stopped");
                    break;
                }
            }
        });

        spawn_packet_router(
            tcp_handler,
            udp_handler,
            dns_handler,
            tun_rx,
            device_tx,
            tcp_rewriter,
        );
        Ok(injector)
    }

    /// Start packet routing over caller-provided channels.
    ///
    /// The returned sender accepts inbound IP packets. The returned receiver
    /// yields outbound IP packets generated by the injector.
    pub async fn run_with_channels(
        self,
        tcp_handler: Arc<dyn TunTcpHandler>,
        udp_handler: Arc<dyn TunUdpHandler>,
        dns_handler: Arc<dyn TunDnsHandler>,
    ) -> Result<
        (
            Arc<dyn mesh::tun::TunInjector>,
            mpsc::UnboundedSender<Vec<u8>>,
            mpsc::UnboundedReceiver<Vec<u8>>,
        ),
        anyhow::Error,
    > {
        let (incoming_tx, incoming_rx) = mpsc::unbounded_channel::<Vec<u8>>();
        let (outgoing_tx, outgoing_rx) = mpsc::unbounded_channel::<Vec<u8>>();
        let injector = Arc::new(injector::MeshTunInjector::new(outgoing_tx.clone()));
        let tcp_rewriter = self.tcp_rewriter()?;
        spawn_packet_router(
            tcp_handler,
            udp_handler,
            dns_handler,
            incoming_rx,
            outgoing_tx,
            tcp_rewriter,
        );
        Ok((injector, incoming_tx, outgoing_rx))
    }

    fn open_tun_device(&self) -> Result<tun_rs::AsyncDevice, anyhow::Error> {
        if let Some(fd) = self.config.fd {
            return unsafe { tun_rs::AsyncDevice::from_fd(fd) }
                .map_err(|error| anyhow::anyhow!("TUN FD error: {error}"));
        }

        let mut builder = tun_rs::DeviceBuilder::new();
        if let Some(name) = &self.config.name {
            builder = builder.name(name);
        }
        builder
            .mtu(self.config.mtu as u16)
            .build_async()
            .map_err(|error| anyhow::anyhow!("TUN create error: {error}"))
    }

    fn tcp_rewriter(&self) -> Result<Option<TcpRewriter>, anyhow::Error> {
        self.config
            .tcp_rewrite
            .then(|| TcpRewriter::new(self.config.tcp_rewrite_config.clone()))
            .transpose()
    }
}

fn spawn_packet_router(
    tcp_handler: Arc<dyn TunTcpHandler>,
    udp_handler: Arc<dyn TunUdpHandler>,
    dns_handler: Arc<dyn TunDnsHandler>,
    mut incoming_rx: mpsc::UnboundedReceiver<Vec<u8>>,
    outgoing_tx: mpsc::UnboundedSender<Vec<u8>>,
    tcp_rewriter: Option<TcpRewriter>,
) {
    let tcp_proxy = tcp_proxy::TcpProxyManager::new(outgoing_tx.clone(), tcp_handler);
    tokio::spawn(async move {
        let mut tcp_rewriter = tcp_rewriter;
        while let Some(packet) = incoming_rx.recv().await {
            match packet::parse_ip_packet(&packet) {
                packet::TunPacket::Udp(packet)
                    if packet.src_port == 53 || packet.dst_port == 53 =>
                {
                    let handler = dns_handler.clone();
                    tokio::spawn(async move {
                        handler.handle_dns(packet).await;
                    });
                }
                packet::TunPacket::Udp(packet) => {
                    let handler = udp_handler.clone();
                    tokio::spawn(async move {
                        handler.handle_udp(packet).await;
                    });
                }
                packet::TunPacket::Tcp(tcp) => {
                    if let Some(rewriter) = tcp_rewriter.as_mut() {
                        let result = if tcp.dst_addr == IpAddr::V4(rewriter.config().proxy_addr) {
                            rewriter.translate_inbound(&packet)
                        } else {
                            rewriter.translate_outbound(&packet)
                        };
                        match result {
                            Ok(Some(packet)) => {
                                let _ = outgoing_tx.send(packet);
                            }
                            Ok(None) => {}
                            Err(error) => {
                                tracing::warn!(%error, "TCP rewrite failed");
                            }
                        }
                        continue;
                    }
                    tracing::debug!(
                        src = %std::net::SocketAddr::new(tcp.src_addr, tcp.src_port),
                        dst = %std::net::SocketAddr::new(tcp.dst_addr, tcp.dst_port),
                        syn = tcp.syn,
                        ack = tcp.ack,
                        "TCP packet observed; routing to TcpProxyManager"
                    );
                    tcp_proxy.handle_packet(tcp).await;
                }
                packet::TunPacket::Other => {}
            }
        }
    });
}
